os: Visual Studio 2017

version: stator-{build}

platform:
  - Win32
  - x64

configuration: Release

install:
  - cmd: cd c:\projects\dynamo
  - cmd: git submodule init
  - cmd: git submodule update

clone_folder: c:\projects\dynamo

before_build:
  - echo "#  Configuring..."
  - cmd: md build
  - cmd: cd build
  - echo Running cmake...
  - cmd: if "%platform%"=="Win32" cmake .. -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN32%"
  - cmd: if "%platform%"=="x64" cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN64%"
  - cmd: cd ..

build_script:
  - echo "#  Building..."
  - cd build
  - cmake --build . --config %configuration%
  - cd ..

test_script:
  - cd build
  - set CTEST_OUTPUT_ON_FAILURE=1
  - ctest --build-config %configuration%
  - cd ..

